"""classId on deck

Revision ID: a22603791a12
Revises: e76d1d3037e5
Create Date: 2021-01-11 13:11:18.861679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22603791a12'
down_revision = 'e76d1d3037e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('classId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'decks', 'classes', ['classId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_column('decks', 'classId')
    # ### end Alembic commands ###
