"""actual notifications

Revision ID: c5e70ea2a555
Revises: c58027a13db5
Create Date: 2021-01-08 13:39:54.599902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e70ea2a555'
down_revision = 'c58027a13db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('forUserId', sa.Integer(), nullable=True),
    sa.Column('forRequestId', sa.Integer(), nullable=True),
    sa.Column('noteType', sa.Enum('request', 'approve', 'deny', name='type'), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forRequestId'], ['enrollment_requests.id'], ),
    sa.ForeignKeyConstraint(['forUserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_forUserId'), 'notification', ['forUserId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_forUserId'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
