"""deck ownerId

Revision ID: 4817b302cf88
Revises: dd74b84bc350
Create Date: 2021-01-05 13:14:38.123555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4817b302cf88'
down_revision = 'dd74b84bc350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('ownerId', sa.Integer(), nullable=False))
    op.drop_constraint('decks_owner_fkey', 'decks', type_='foreignkey')
    op.create_foreign_key(None, 'decks', 'users', ['ownerId'], ['id'])
    op.drop_column('decks', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.create_foreign_key('decks_owner_fkey', 'decks', 'users', ['owner'], ['id'])
    op.drop_column('decks', 'ownerId')
    # ### end Alembic commands ###
