"""classes and enrollments

Revision ID: 6fbc7d24fbf3
Revises: 4817b302cf88
Create Date: 2021-01-08 12:55:55.081407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbc7d24fbf3'
down_revision = '4817b302cf88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.Column('classId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classId'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('classes')
    # ### end Alembic commands ###
