"""add key column to class

Revision ID: 49ff5c41667d
Revises: e1eee31a5b27
Create Date: 2021-01-08 15:31:59.326302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ff5c41667d'
down_revision = 'e1eee31a5b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('key', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_classes_key'), 'classes', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_key'), table_name='classes')
    op.drop_column('classes', 'key')
    # ### end Alembic commands ###
